### ISSUE TITLE
TypeScript + CommonJS support

### ISSUE THREAD

**Issue by Jackman3005** [ehmicky/modern-errors#3]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

I am unable to import this library into my codebase. I think it is because the published version is not compiled to module system I can use (?).

It's quite possible there is something on my side that is causing the issue, or some configuration I could change to get it to work, but we already have > 80 other dependencies in our API that are not having any issues importing. (It's an express API)

Thanks in advance for any help, I'm quite excited to give this library a try!

### Steps to reproduce

1. Import and use the library
```typescript
import ModernError from "modern-errors";

const BaseError = ModernError.subclass("BaseError");
throw new BaseError("test");
```
2. Start app with `ts-node-dev`
3. See following stack trace:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jack/workspace/my-project/api/node_modules/modern-errors/build/src/main.js from /Users/jack/workspace/my-project/api/src/index.ts not supported.
Instead change the require of main.js in /Users/jack/workspace/my-project/api/src/index.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:114:20)
    at Object.nodeDevHook [as .js] (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/jack/workspace/my-project/api/src/index.ts:68:41)
    at Module._compile (/Users/jack/workspace/my-project/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:69:33)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:114:20)
    at require.extensions.<computed> (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/Users/jack/workspace/my-project/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Object.require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:95:24)
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["es2021"],
    "target": "es2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "rootDir": "./",
    "outDir": ".build",
    "allowJs": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": ["node_modules/@types", "generated"],
  },
  "exclude": ["node_modules"]
}
```

### Environment

 ```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.1
```

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @Jackman3005,

Thanks a lot for reaching out!

## Problem

The core problem is that `modern-errors` [is using ES modules](https://github.com/ehmicky/modern-errors#install) while your configuration is using CommonJS. Your current TypeScript configuration is using `"module": "commonjs"` and`"moduleResolution": "node"` which transpiles `import ModernError from "modern-errors"` to `const ModernError = require("modern-errors")`. However, Node.js [does not allow using `require()`](https://nodejs.org/api/esm.html#require) on ES modules.

## Solution 1

The best solution to this is to configure TypeScript to [support ES modules](https://www.typescriptlang.org/docs/handbook/esm-node.html), i.e. use `"module": "nodenext"` and `"moduleResolution": "nodenext"`. 

I understand this is a big change and might not be worth it for you when trying to add a single library. However, this is a general problem you will encounter not only with `modern-errors` but with any dependencies using ES modules. The >80 dependencies you are currently importing are not using ES modules, but the number of libraries that have migrated to ES modules is rapidly growing right now. 

CommonJS is deprecated by Node.js. Node 14 (the oldest Node.js version still officially supported) works natively with ES modules. For this reason, `modern-errors` should remain ES modules only.

## Solution 2 (details)

The other option is to use a dynamic `import()`: `const ModernError = await import("modern-errors")`. Node.js allows dynamic imports of ES modules from CommonJS. 

This last solution has a problem though: `modern-errors` is meant to be imported on the top-level scope, because it is much simpler to create error classes in the top-level scope instead of inside a function. However, top-level `await` is not supported by TypeScript with `"module": "commonjs"`. Instead, [`"module": "nodenext"`](https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds) should be used. The main difference is: instead of outputting only CommonJS, TypeScript will output either CommonJS or ES modules, depending on which one it detects. In particular, it will output ES modules if your `package.json` is using `"type": "module"` or a file has a `.mjs` file extension. If you're currently using a CommonJS configuration, you are probably not doing either, i.e. I believe this change might work without any issues for you.

The other problem with dynamic imports is that they are missing type information. This can be solved by using the following type assertion: `as unknown as typeof import('modern-errors').default`.

## Solution 2 (summary)

  - `"module": "nodenext"` instead of `"module": "commonjs"` in `tsconfig.json`
  - `const ModernError = await import("modern-errors") as unknown as typeof import('modern-errors').default`

----

Please let me know what you think.

**Comment by Jackman3005** [comment]
Hey @ehmicky thanks for getting back to me so quickly. I'll take a look at the options and see what works for us. Cheers!

**Comment by Jackman3005** [comment]
I guess part of the issue is I was not aware that "commonjs" is deprecated in Node 14. I got confused by the following in the [Official Typescript Docs for Module field](https://www.typescriptlang.org/tsconfig#module):

> Sets the module system for the program. See the [Modules](https://www.typescriptlang.org/docs/handbook/modules.html) reference page for more information. You very likely want "CommonJS" for node projects.

**Comment by Jackman3005** [comment]
I notice other libraries I use actually provide both commonjs and esm files. What would the problem be for modern-errors to provide multiple module systems in the NPM package? I imagine I'm not the only one that isn't on ESM yet..

**Comment by ehmicky** [comment]
Please note I was referring to Node.js (not TypeScript) deprecating CommonJS. However the term "deprecating" was rather incorrect: Node.js is not deprecating nor planning to ever remove support for CommonJS. A more accurate way to put it would be:  they are planning to focus primarily on ES modules for the present and future (see [discussion](https://github.com/nodejs/node/issues/33954#issuecomment-790053069) about this).

I have tried double packaging in the past, and it turned out to be quite complicated for bigger projects like `modern-errors`. Considering CommonJS is a legacy module system, I do not think this is something that would be added to this project unfortunately.

**Comment by Jackman3005** [comment]
Unfortunately it looks like we will not be able to use your error framework for now due to the lack of double packaging/support for CommonJS modules out of the box. It'd be great if we could more readily support the new module system in our code-base or if the hacks to use it while we still are using CommonJS were less hacky. 

It looks great in concept and seems like something that would really clean up and improve our error handling system. One day I hope to be able to use it!
