### ISSUE TITLE
support for mandatory props along with type-check support

### ISSUE THREAD

**Issue by bhvngt** [ehmicky/modern-errors#5]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

Thanks for this wonderful library. 

Is it possible to define mandatory props. I have a situation where I would like consumer of my error class to pass certain required props.

### Describe the solution you'd like

 For example, 

```typescript
const BaseError = ModernError.subclass('BaseError', {
	props: {userId: 1}  as {userId: number}
})

const error = new BaseError('Wrong user name', {
	props: {} //would be great if there is type-checking of props here
})
```

It will be great if when I am creating BaseError, there is a way to prompt/type-check for mandatory props.

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @bhvngt,

Thanks for the feedback, that's an interesting idea!

We need to distinguish 5 different features here:
  1. Assigning `props` default values
  2. Allowing `props` to be passed to `new BaseError(...)`
  3. Typing the `props` default values
  4. Typing the `props` passed to `new BaseError(...)`
  5. Validating that `props` are defined, i.e. making them required

Currently, `props` is designed only to fulfill 1, 2 and 3.

In terms of typing, when an error is instantiated with `props`, typing its `props` correctly works:

```ts
const error = new BaseError('Wrong user name', {
	props: { userId: 1 } as { userId: number }
}) // error.userId is typed as a number
```

On the other hand, when declaring an error class, typing `props` does not type its value when instantiated with `new BaseError(...)`. Instead, it types the default value being declared. For example:

```ts
const BaseError = ModernError.subclass('BaseError', {
	props: {userId: 1}  as { userId: number }
})
const error = new BaseError('message') // error.userId is typed as a number
```

This allows typing that default value, since it ends up being assigned to most error instances of that class. 

In other words, `props` is not currently designed for the features 4 and 5 indicated above: typing the `props` based to `new BaseError(...)`, and making them required.

I think those are useful features. However, simplicity is a key goal of `modern-errors`. Based on this, I would suggest one of the two following solutions.

First, using [the `custom` option](https://github.com/ehmicky/modern-errors#-custom-logic). In the `constructor`, you can throw an error if the wrong `props` are being passed.

The other solution would be to [create a plugin](https://github.com/ehmicky/modern-errors/blob/main/docs/plugins.md) for it. It might actually be quite simple! The end result could look like this:

```ts
import modernErrorsRequired from 'modern-errors-required'

const BaseError = ModernError.subclass('BaseError', {
  plugins: [modernErrorsRequired],
  props: {userId: 1}  as {userId: number},
  required: ['userId'],
})
```

Unfortunately, neither of those solutions would solve type checking.

Please let me know what you think.

**Comment by bhvngt** [comment]
Thanks @ehmicky for your very explained reply.

I was trying out the [the custom option](https://github.com/ehmicky/modern-errors#-custom-logic). It seems to workout fine with a slight bit of issue. Since `options` is an optional arg. Any arg that I add after `options` has to be optional too.

Here's an example

```typescript
import ModernError, {InstanceOptions} from "modern-errors";

export const InvalidInputError = ModernError.subclass('InvalidInputError', {
    custom: class extends ModernError {
        #schemaId?: string;
        constructor(message: string, options?: InstanceOptions, schemaId?: string) {
            super(message, options);
            this.#schemaId = schemaId;
        }

        get schemaId() {return this.#schemaId}
    }
})
```

It also type-checks custom parameter as `extra`

<img width="698" alt="image" src="https://user-images.githubusercontent.com/79074469/212948447-966ccfae-8957-4279-8126-b834f7fd73bd.png">

Your second solution is neat. With that I can do a runtime check. 

One more option could be to create custom Error class with `required props` as `constructor params` and treat the class as a wrapper around ModernError subclass. This also has the extra benefit of doing a type-check

 Since with these options, my use case will be well served and hence I will close this issue.

**Comment by ehmicky** [comment]
I'm happy your problem is solved @bhvngt! :clap: 

Thanks for sharing the third solution. This could be a solution for other issues as well, so that's a nice idea.

@all-contributors Could please add @bhvngt for ideas, question?

**Comment by ehmicky** [comment]
The contributors update was wrong and did not properly add you on the README @bhvngt. I just fixed it :+1:

**Comment by realfresh** [comment]
Hey @ehmicky, lovely library. Can you see anything wrong with this solution:

```
import ModernError, {type InstanceOptions} from "modern-errors";

type ErrorProps = Record<string, unknown>;

class BaseError<P extends ErrorProps> extends ModernError {
  constructor(msg: string, options?: Omit<InstanceOptions, "props"> & {props: P}) {
    super(msg, options);
  }
}

class ValidationError extends BaseError<{fields: string[]}> {}
```

This does give strict type checking with creating `new ValidationError(..)`
